// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_dotNet.Persistence;

#nullable disable

namespace WebApp_dotNet.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApp_dotNet.Persistence.ProjectDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProjectDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2025, 10, 10, 11, 30, 15, 131, DateTimeKind.Local).AddTicks(1940),
                            Title = "Learn ASP.NET Core with MVC",
                            UserName = "Bob@kth.se"
                        });
                });

            modelBuilder.Entity("WebApp_dotNet.Persistence.TaskDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Follow the tutorials",
                            LastUpdated = new DateTime(2025, 10, 10, 11, 30, 15, 131, DateTimeKind.Local).AddTicks(3308),
                            ProjectId = -1,
                            status = 0
                        },
                        new
                        {
                            Id = -2,
                            Description = "Do it yourself!",
                            LastUpdated = new DateTime(2025, 10, 10, 11, 30, 15, 131, DateTimeKind.Local).AddTicks(3392),
                            ProjectId = -1,
                            status = 1
                        });
                });

            modelBuilder.Entity("WebApp_dotNet.Persistence.TaskDb", b =>
                {
                    b.HasOne("WebApp_dotNet.Persistence.ProjectDb", "ProjectDB")
                        .WithMany("TaskDBs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectDB");
                });

            modelBuilder.Entity("WebApp_dotNet.Persistence.ProjectDb", b =>
                {
                    b.Navigation("TaskDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
